### ISSUE TITLE
Uncaught Exception when using Terrainruler

### ISSUE THREAD

**Issue by emomgo3** [velara/pf2edragruler#35]
![image](https://user-images.githubusercontent.com/48028314/203685451-c7ca76d4-10f7-44b9-9c12-8993edbe9e3d.png)
This exception occurs when trying to measure a distance affected by difficult terrain.
After some troubleshooting with "find the culprit" i seem to have narrowed down the problem to an interaction between "pf2e drag ruler integration" and "terrain ruler".

Disabling either of them restores any functionality with no issue.
However using both of them throws this exception.

**Comment by velara** [comment]
You're definitely in the right spot for your report as the stack trace indicates that PF2e drag ruler integration is responsible. 

However, I have insufficient information to replicate your bug. When I try and measure distance effected by difficult terrain with either the ruler tool or by dragging a token I do not get that error. 

The stack trace seems to be suggesting that your terrain object does not have a .document entry, which would be very odd. 

What are the numbered versions of Drag Ruler, Enhanced Terrain Layer, Terrain Ruler, Socket Lib, PF2e Drag Ruler Integration, the PF2e system and Foundry that you're running? 

How did you place the terrain? Was is the rectangle, ellipse, freehand or polygon tool? Was it new terrain you had just drawn or had in been on your map for several system/foundry/enhanced terrain ruler updates?

**Comment by emomgo3** [comment]
Drag Ruler: 1.13.2
Enhanced Terrain Layer: 10.6
Terrain Ruler: 1.7.3
Socket Lib: 1.0.12
Pf2e Dragruler Integration: 2.1.2
Pf2e System: 4.4.1
Foundry: Build 290

After Some Testing i found out that any drawn difficult terrain seems to work as intended.
The Exception occurs when dragging through other tokens, which are supposed to also work as difficult terrain.
Old and new created Actors, meaning ones created in V9 Foundry and v10 Foundry, both throw this exception.

Edit: it may be of importance that i'm hosting on forgeVTT and it may be an issue on their side.

**Comment by velara** [comment]
An issue with the handling of “treat tokens” as difficult terrain seems like the most likely culprit. I’ll hopefully be able to replicate the issue and fix it tomorrow.

Thanks for doing the testing!

**Comment by emomgo3** [comment]
> libWrapper-wrapper.js:669 Uncaught TypeError: Cannot read properties of undefined (reading 'actor')
[Detected 5 packages: pf2e-dragruler, enhanced-terrain-layer, terrain-ruler, lib-wrapper, drag-ruler]
    at PF2eRuleProvider.calculateCombinedCost (main.js:112:175)
    at calculateCombinedCost (api.js:121:38)
    at TerrainLayer.costWithTerrain (terrainlayer.js:287:26)
    at TerrainLayer.cost (terrainlayer.js:297:21)
    at getCostEnhancedTerrainlayer (measure.js:26:24)
    at measure.js:95:14
    at Array.map (<anonymous>)
    at measureDistancesSquare (measure.js:34:18)
    at measureDistances (measure.js:20:10)
    at DragRulerRuler.computeDistance (main.js:77:21)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁Ruler.prototype._computeDistance#0 (libWrapper-wrapper.js:189:20)
    at DragRulerRuler._computeDistance (ruler.js:262:18)
    at DragRulerRuler.measure (foundry.js:32239:10)
    at DragRulerRuler.measure (ruler.js:80:18)
    at DragRulerRuler._onMouseMove (foundry.js:32577:12)
    at Canvas._onDragLeftMove (foundry.js:24329:42)
    at MouseInteractionManager.callback (foundry.js:27723:45)
    at MouseInteractionManager._handleDragMove (foundry.js:28080:17)
    at MouseInteractionManager._handleMouseMove (foundry.js:28052:22)
    at a.emit (index.js:202:33)
    at r.dispatchEvent (interaction.min.mjs:8:12235)
    at r.processPointerMove (interaction.min.mjs:8:17255)
    at t.recursiveFindHit (interaction.min.mjs:8:4098)
    at t.findHit (interaction.min.mjs:8:4157)
    at r.processInteractive (interaction.min.mjs:8:12841)
    at r.onPointerMove (interaction.min.mjs:8:16687)
    
I'm sorry for reopening this issue, but after the fix i seem to have found another uncaught exception that occurs when using the "measure distance" tool instead of dragging a token directly. This also seems to happen when measuring through drawn difficult terrain. Same numbered versions.

Also, this may simply be an issue on my side, but living tokens do not seem to count as difficult terrain anymore.
The option in enhanced-terrain-layer for including living tokens is set to "Any".

Thank you for your work btw!

**Comment by velara** [comment]
I’ll see if I can reproduce your issue with the measure tool.

In so far as the enhanced terrain layer setting are concerned the current version doesn’t exactly respect its settings. The PF2e system doesn’t use the friendly hostile neutral token setting anymore and has removed them from the interface. So the integration will only treat a live token as difficult terrain if it is alliance doesn’t match. Opposition tokens will not treat other opposition tokens as difficult terrain and like way for allied tokens. But a player owned token should treat an NPC as difficult terrain unless you set their alliance to be allied with the players.

**Comment by velara** [comment]
Found the bug. I forgot to wrap the alliance code within the logic that handles non-token sources. Should have a fix out soon.
